# Type stub for psycopg2
from typing import Any, Optional

class connection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cursor(self) -> Any: ...
    def close(self) -> None: ...
    def set_isolation_level(self, level: Any) -> None: ...

class cursor:
    def execute(self, query: str, vars: Optional[Any] = None) -> None: ...
    def fetchone(self) -> Optional[tuple]: ...
    def fetchall(self) -> list: ...
    def close(self) -> None: ...

class Error(Exception):
    pass

def connect(*args: Any, **kwargs: Any) -> connection: ... 