"""add_user_id_to_chat_messages

Revision ID: 9df835b580ca
Revises: 1832851c1af5
Create Date: 2025-06-04 16:07:27.064542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df835b580ca'
down_revision = '1832851c1af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    
    # Add user_id column to chat_messages table
    op.add_column('chat_messages', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Populate user_id from the session's user_id
    op.execute("""
        UPDATE chat_messages 
        SET user_id = (
            SELECT user_id 
            FROM chat_sessions 
            WHERE chat_sessions.id = chat_messages.session_id
        )
    """)
    
    # Make user_id NOT NULL after populating data
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # Add foreign key constraint
    op.create_foreign_key('chat_messages_user_id_fkey', 'chat_messages', 'users', ['user_id'], ['id'])
    
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('consultation_requests_doctor_id_fkey', 'consultation_requests', type_='foreignkey')
    op.drop_constraint('consultation_requests_chat_session_id_fkey', 'consultation_requests', type_='foreignkey')
    op.drop_constraint('consultation_requests_user_id_fkey', 'consultation_requests', type_='foreignkey')
    op.drop_constraint('doctors_email_key', 'doctors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('doctors_email_key', 'doctors', ['email'])
    op.create_foreign_key('consultation_requests_user_id_fkey', 'consultation_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key('consultation_requests_chat_session_id_fkey', 'consultation_requests', 'chat_sessions', ['chat_session_id'], ['id'])
    op.create_foreign_key('consultation_requests_doctor_id_fkey', 'consultation_requests', 'doctors', ['doctor_id'], ['id'])
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # Drop foreign key constraint and column
    op.drop_constraint('chat_messages_user_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'user_id')
    
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    # ### end Alembic commands ### 