"""Add file support to chat messages

Revision ID: b2204deb1260
Revises: bdb97b762f4b
Create Date: 2025-06-08 00:12:44.756845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2204deb1260'
down_revision = 'bdb97b762f4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('chat_messages', sa.Column('file_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'file_type')
    op.drop_column('chat_messages', 'file_path')
    # ### end Alembic commands ### 