"""Add HealthKit tables

Revision ID: bdb97b762f4b
Revises: 9df835b580ca
Create Date: 2025-06-06 21:04:14.664668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb97b762f4b'
down_revision = '9df835b580ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('consultation_requests_doctor_id_fkey', 'consultation_requests', type_='foreignkey')
    op.drop_constraint('consultation_requests_user_id_fkey', 'consultation_requests', type_='foreignkey')
    op.drop_constraint('consultation_requests_chat_session_id_fkey', 'consultation_requests', type_='foreignkey')
    op.drop_constraint('doctors_email_key', 'doctors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('doctors_email_key', 'doctors', ['email'])
    op.create_foreign_key('consultation_requests_chat_session_id_fkey', 'consultation_requests', 'chat_sessions', ['chat_session_id'], ['id'])
    op.create_foreign_key('consultation_requests_user_id_fkey', 'consultation_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key('consultation_requests_doctor_id_fkey', 'consultation_requests', 'doctors', ['doctor_id'], ['id'])
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    # ### end Alembic commands ### 